export const  CHANGE_EMAIL = 'change_email'
export const  CHANGE_PASSWORD =  'change_password'
export const  CHANGE_NAME = 'change_name'
export const  LOGIN_SUCESS = 'login_sucess'
export const  LOGIN_ERROR = 'login_error'
export const  REGISTER_SUCESS = 'sucess'
export const  REGISTER_ERROR = 'register_error'
export const LOADING_LOGIN = 'loading_login'
export const LOADING_REGISTER = 'loading_register'

//appActions
export const CHANGE_CONTACT_EMAIL = 'change_contact_email'
export const ADD_CONTACT = 'add_contact'
export const ADD_CONTACT_ERROR = 'add_contact_error'
export const CONTACT_LIST_USER = 'contact_list_user'
export const ADD_CONTACT_SUCESS = 'add_contact_sucess'
export const CHANGE_MESSAGE = 'change_message'
export const SEND_MESSAGE = 'send_message'